# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('octavo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='octavo.Genre')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='search',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='search',
            name='level',
        ),
        migrations.RemoveField(
            model_name='search',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='search',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='search',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='search',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='search',
            name='sem',
            field=models.TextField(),
        ),
    ]
