# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octavo', '0002_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='stream',
            new_name='sem',
        ),
    ]
