# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octavo', '0002_auto_20160730_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='parent',
        ),
    ]
