# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octavo', '0003_remove_subject_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='DB',
        ),
    ]
